#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py makemigrations
python manage.py migrate
# python manage.py runserver_plus 0.0.0.0:8000
# python manage.py shell_plus --notebook
uvicorn metadata.asgi:application --host 0.0.0.0 --reload --reload-include '*.html' # use if serving async
