exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
      - id: check-xml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: sort-simple-yaml
      - id: check-shebang-scripts-are-executable
      - id: check-case-conflict
      - id: check-ast
      - id: check-symlinks

  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ['--check', '--no-update']

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.5
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - Flake8-pyproject
          - flake8-isort

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: ["pydocstyle[toml]"]
        args: [--config, ./pyproject.toml]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.3
    hooks:
      - id: docformatter
        args: [--in-place, --config, ./pyproject.toml]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      args: [-c, pyproject.toml]
      additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [--config-file, ./pyproject.toml]
        verbose: true
        entry: bash -c 'mypy "$@" || true' --
        additional_dependencies:
          - types-python-dateutil
          - django-stubs[compatability-mypy]
          - python-dotenv
          - whitenoise
          - django-extensions
          - django-debug-toolbar
          - azure-storage-blob
          - django_pandas
          - tqdm
          - psycopg[binary]
          - validators
# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
