[tool.poetry]
name = "metadata"
version = "0.1.0"
description = "Metadata database management through Django for Living with Maachines."
authors = ["Kalle Westerling <kalle.westerling@bl.uk>"]

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
django = "^4.0.7"
seaborn = "^0.11.2"
pandas = "^1.4.1"
ipython = "^8.4.0"
jupyter = "^1.0.0"
django-pandas = "^0.6.6"
django-extensions = "^3.2.0"
colorama = "^0.4.5"
azure-storage-blob = "^12.13.0"

[tool.poetry.dev-dependencies]
pyfakefs = "^4.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
