# Generated by Django 3.2.12 on 2022-05-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazetteer', '0001_create_initial_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincounty',
            name='admin_county_label',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='admincounty',
            name='admin_county_wikidata_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_label',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_wikidata_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='historiccounty',
            name='hcounty_label',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='historiccounty',
            name='hcounty_wikidata_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='placeofpublication',
            name='geonames_ids',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='placeofpublication',
            name='place_label',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='placeofpublication',
            name='place_wikidata_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterModelTable(
            name='placeofpublication',
            table='place_of_publication',
        ),
    ]
