# Generated by Django 3.2.12 on 2022-04-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gazetteer', '0001_create_initial_schema'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='placeofpublication',
            table='place_of_publication',
        ),
    ]
