# Generated by Django 3.2.12 on 2022-05-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gazetteer', '0002_alter_placeofpublication_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeofpublication',
            name='geopoint',
        ),
    ]
