# Generated by Django 3.2.12 on 2022-05-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazetteer', '0002_alter_placeofpublication_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeofpublication',
            name='place_label',
            field=models.CharField(default='', max_length=255),
        ),
    ]
