# Generated by Django 4.2.5 on 2023-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("fulltext", "0001_initial"),
        ("fulltext", "0002_fulltext_compressed_path_fulltext_zip_path"),
        ("fulltext", "0003_fulltext_path"),
        ("fulltext", "0004_fulltext_fixture_path"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fulltext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "compressed_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("path", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "fixture_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
