# Generated by Django 4.2.5 on 2023-10-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fulltext", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulltext",
            name="errors",
            field=models.TextField(blank=True, null=True),
        ),
    ]
