# Generated by Django 4.2.5 on 2023-10-14 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fulltext", "0002_fulltext_errors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fulltext",
            name="fixture_path",
        ),
    ]
