# Generated by Django 4.1.1 on 2022-09-30 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fulltext", "0001_initial"),
        ("newspapers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="fulltext",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fulltext.fulltext",
            ),
        ),
    ]
