# Generated by Django 4.0.5 on 2022-06-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gazetteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitchells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default=None, max_length=255, null=True)),
                ('political_leaning_1', models.CharField(default=None, max_length=255, null=True)),
                ('political_leaning_2', models.CharField(default=None, max_length=255, null=True)),
                ('political_leaning_raw', models.JSONField(null=True)),
                ('price_1', models.CharField(default=None, max_length=255, null=True)),
                ('price_2', models.CharField(default=None, max_length=255, null=True)),
                ('price_raw', models.JSONField(null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('date_established_raw', models.JSONField(null=True)),
                ('day_of_publication_raw', models.CharField(default=None, max_length=255, null=True)),
                ('place_of_circulation_raw', models.CharField(default=None, max_length=2550, null=True)),
                ('publication_district_raw', models.CharField(default=None, max_length=255, null=True)),
                ('publication_county_raw', models.CharField(default=None, max_length=255, null=True)),
                ('organisations', models.CharField(default=None, max_length=255, null=True)),
                ('persons', models.CharField(default=None, max_length=510, null=True)),
                ('place_of_publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gazetteer.placeofpublication', verbose_name='place_of_publication')),
            ],
            options={
                'db_table': 'mitchells',
            },
        ),
    ]
