# Generated by Django 3.2.12 on 2022-04-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gazetteer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitchells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('political_leaning_1', models.CharField(default='', max_length=30)),
                ('political_leaning_2', models.CharField(default='', max_length=30)),
                ('political_leaning_raw', models.JSONField()),
                ('price_1', models.CharField(default='', max_length=30)),
                ('price_2', models.CharField(default='', max_length=30)),
                ('price_raw', models.JSONField()),
                ('year', models.DateField(blank=True, null=True)),
                ('date_established_raw', models.JSONField()),
                ('day_of_publication_raw', models.CharField(default='', max_length=30)),
                ('place_of_circulation_raw', models.CharField(default='', max_length=255)),
                ('publication_district_raw', models.CharField(default='', max_length=255)),
                ('publication_county_raw', models.CharField(default='', max_length=255)),
                ('organisations', models.CharField(default='', max_length=255)),
                ('persons', models.CharField(default='', max_length=255)),
                ('place_of_publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gazetteer.placeofpublication', verbose_name='place_of_publication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
