# Generated by Django 3.2.12 on 2022-04-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press_directories', '0001_creating_initial_schema'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mitchells',
            table='mitchells',
        ),
    ]
