# Generated by Django 3.2.12 on 2022-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_directories', '0002_alter_mitchells_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitchells',
            name='day_of_publication_raw',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='political_leaning_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='political_leaning_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='price_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='price_2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
