# Generated by Django 3.2.12 on 2022-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_directories', '0003_alter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitchells',
            name='place_of_circulation_raw',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
