# Generated by Django 3.2.12 on 2022-05-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_directories', '0005_alter_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitchells',
            name='day_of_publication_raw',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='organisations',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='persons',
            field=models.CharField(default=None, max_length=510),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='place_of_circulation_raw',
            field=models.CharField(default=None, max_length=2550),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='political_leaning_1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='political_leaning_2',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='price_1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='price_2',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='publication_county_raw',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='publication_district_raw',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
