# Generated by Django 3.2.12 on 2022-05-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press_directories', '0007_allow_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitchells',
            name='date_established_raw',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mitchells',
            name='political_leaning_raw',
            field=models.JSONField(null=True),
        ),
    ]
