# Generated by Django 4.2.7 on 2024-01-18 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newspapers", "0002_fulltext"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fulltext",
            options={"verbose_name": "full text", "verbose_name_plural": "full texts"},
        ),
    ]
