# Generated by Django 4.1.7 on 2023-02-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0004_item_title_char_count_item_title_truncated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default=None, max_length=800),
        ),
    ]
