# Generated by Django 4.1.7 on 2023-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0005_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default=None, max_length=3000),
        ),
    ]
