# Generated by Django 4.1.7 on 2023-03-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0006_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(default=None, max_length=800),
        ),
    ]
