# Generated by Django 4.2 on 2023-04-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0006_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
