# Generated by Django 4.1.7 on 2023-04-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0007_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
