# Generated by Django 4.2.3 on 2023-07-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspapers", "0008_alter_item_title"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["issue_code"], name="newspapers__issue_c_e41b28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["item_code"], name="newspapers__item_co_417bcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newspaper",
            index=models.Index(
                fields=["publication_code"], name="newspapers__publica_bfbe2a_idx"
            ),
        ),
    ]
