# Generated by Django 4.2.4 on 2023-08-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspapers", "0009_issue_newspapers__issue_c_e41b28_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataprovider",
            name="code",
            field=models.SlugField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="dataprovider",
            name="legacy_code",
            field=models.SlugField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
