# Generated by Django 3.2.13 on 2022-06-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('press_directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=600)),
                ('collection', models.CharField(default=None, max_length=600)),
                ('source_note', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'data_providers',
            },
        ),
        migrations.CreateModel(
            name='Digitisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xml_flavour', models.CharField(default=None, max_length=255)),
                ('software', models.CharField(default=None, max_length=600)),
                ('mets_namespace', models.CharField(default=None, max_length=255)),
                ('alto_namespace', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'digitisations',
            },
        ),
        migrations.CreateModel(
            name='Ingest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lwm_tool_name', models.CharField(default=None, max_length=600)),
                ('lwm_tool_version', models.CharField(default=None, max_length=600)),
                ('lwm_tool_source', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'ingests',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_code', models.CharField(default=None, max_length=600)),
                ('issue_date', models.DateField()),
                ('input_sub_path', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'issues',
            },
        ),
        migrations.CreateModel(
            name='MitchellsPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('mitchells', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='press_directories.mitchells', verbose_name='mitchells')),
            ],
            options={
                'db_table': 'mitchells_publications',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication_code', models.CharField(default=None, max_length=600)),
                ('title', models.CharField(default=None, max_length=255)),
                ('location', models.CharField(default=None, max_length=255)),
                ('mitchells_publication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newspapers.mitchellspublication', verbose_name='mitchells')),
            ],
            options={
                'db_table': 'publications',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(default=None, max_length=600)),
                ('title', models.TextField(default=None)),
                ('item_type', models.CharField(default=None, max_length=600)),
                ('word_count', models.IntegerField(db_index=True, null=True)),
                ('ocr_quality_mean', models.FloatField(blank=True, null=True)),
                ('ocr_quality_sd', models.FloatField(blank=True, null=True)),
                ('input_filename', models.CharField(default=None, max_length=255)),
                ('data_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newspapers.dataprovider', verbose_name='data_provider')),
                ('digitisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newspapers.digitisation', verbose_name='digitisation')),
                ('ingest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newspapers.ingest', verbose_name='ingest')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newspapers.issue', verbose_name='issue')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newspapers.publication', verbose_name='publication'),
        ),
    ]
