# Generated by Django 3.2.12 on 2022-04-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('press_directories', '0001_creating_initial_schema'),
        ('newspapers', '0002_alter_primary_key_field_BigAutoField'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitchellsPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('mitchells', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='press_directories.mitchells', verbose_name='mitchells')),
            ],
            options={
                'db_table': 'mitchells_publications',
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='mitchells_publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newspapers.mitchellspublication', verbose_name='mitchells'),
        ),
    ]
