# Generated by Django 3.2.12 on 2022-04-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0003_add_mitchells_publication_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='collection',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='name',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='digitisation',
            name='software',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='lwm_tool_name',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='ingest',
            name='lwm_tool_version',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_code',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_code',
            field=models.CharField(default='', max_length=600),
        ),
    ]
