# Generated by Django 3.2.12 on 2022-04-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0004_change_max_char_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ocr_quality_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ocr_quality_sd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
