# Generated by Django 3.2.12 on 2022-05-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0005_alter_ocr_fields_blank_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
