# Generated by Django 3.2.12 on 2022-05-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0006_alter_title_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title_raw',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='input_filename',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
