# Generated by Django 3.2.12 on 2022-05-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0007_titleraw_vs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='collection',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='name',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='source_note',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='digitisation',
            name='alto_namespace',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='digitisation',
            name='mets_namespace',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='digitisation',
            name='software',
            field=models.CharField(default=None, max_length=600),
        ),
        migrations.AlterField(
            model_name='digitisation',
            name='xml_flavour',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
