# Generated by Django 3.2.12 on 2022-05-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0008_change_to_default_none'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='title_raw',
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(default=None),
        ),
    ]
