# Generated by Django 4.2.5 on 2023-10-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gazetteer", "0001_initial"),
        ("newspapers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default=None, max_length=255, null=True)),
                ("political_leaning_raw", models.JSONField(null=True)),
                ("price_raw", models.JSONField(null=True)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True
                    ),
                ),
                ("date_established_raw", models.JSONField(null=True)),
                (
                    "day_of_publication_raw",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "place_of_circulation_raw",
                    models.CharField(default=None, max_length=2550, null=True),
                ),
                (
                    "publication_district_raw",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "publication_county_raw",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "organisations",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("persons", models.CharField(default=None, max_length=510, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, default=None, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PoliticalLeaning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntryPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(blank=True, default=1, null=True),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mitchells.entry",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mitchells.price",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="EntryPoliticalLeanings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(blank=True, default=1, null=True),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mitchells.entry",
                    ),
                ),
                (
                    "political_leaning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mitchells.politicalleaning",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="issue",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                related_query_name="entry",
                to="mitchells.issue",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="newspaper",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mitchells_entries",
                related_query_name="mitchells_entry",
                to="newspapers.newspaper",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="place_of_publication",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mitchells",
                related_query_name="mitchells",
                to="gazetteer.place",
                verbose_name="place_of_publication",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="political_leanings",
            field=models.ManyToManyField(
                related_name="entries",
                related_query_name="entry",
                through="mitchells.EntryPoliticalLeanings",
                to="mitchells.politicalleaning",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="prices",
            field=models.ManyToManyField(
                related_name="entries",
                related_query_name="entry",
                through="mitchells.EntryPrices",
                to="mitchells.price",
            ),
        ),
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name_plural": "entries"},
        ),
    ]
