# Generated by Django 4.2 on 2023-05-04 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mitchells", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={"verbose_name_plural": "entries"},
        ),
    ]
