# Generated by Django 4.1.3 on 2023-01-19 04:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gazetteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
