name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['main']
    paths-ignore: ['docs/**']

  push:
    branches: ['main', 'geocensus', 'production-deploy']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: config/
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.11'
          # cache: pip
          # cache-dependency-path: |
          #   requirements/base.txt
          #   requirements/local.txt

          # - name: Install and configure Poetry
          #   uses: snok/install-poetry@v1

          # - name: Install package environment to run pre-commit config
          #   run: poetry install --no-interaction --no-root

      - name: Run pre-commit
        uses: pre-commit/action@main
      - name: Update pre-commit
        uses: pre-commit-ci/lite-action@v1.0.1
        if: always()

  # With no caching at all the entire ci process takes 4m 30s to complete!
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@main

      - name: Build the Stack
        run: docker compose -f local.yml build

      # This is currently automated in the build, consider removing
      - name: Run DB Migrations
        run: |
          docker compose -f local.yml run --rm django python manage.py migrate

      - name: Run Django Quick Tests
        run: docker compose -f local.yml run django pytest

      # - name: Run Django Slow Tests
      #   run: docker compose -f local.yml run django pytest -m slow

      - name: Print Django Instance Docker ID
        run: |
          echo "docker compose -f local.yml ps -q django"

      - name: Extract Django Instance Docker ID
        id: save_django_id
        run: |
          echo "docker compose -f local.yml ps -q django"
          export DJANGO_ID=$(docker compose -f local.yml ps -q django)
          echo $DJANGO_ID
          echo "django_id=$DJANGO_ID" >> $GITHUB_ENV
          #
          # django_docker_id=$(docker compose -f local.yml ps -q django)
          # echo "django_id=$django_docker_id" >> "$GITHUB_ENV"

      # - name: Echo docker command
      #   run: |
      #     echo docker compose -f local.yml ps -q django

      - name: Check saved id
        id: check_saved_django_id
        run: echo "${{ env.django_id }}"

      - name: Copy test coverage results
        run: |
          docker cp ${{ env.django_id }}:app/docs/assets/coverage.svg .

      - name: Archive coverage svg
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: app/docs/assets/coverage.svg

      - name: Tear down the Stack
        run: docker compose -f local.yml down
